Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@dofpo 
netology-code
/
aqa-homeworks
Public
Code
Pull requests
Actions
Wiki
Security
Insights
aqa-homeworks/basics/gradle.yml
@ArRomanov
ArRomanov Add github actions example (#21)
Latest commit 1a999d2 on 24 Dec 2021
 History
 1 contributor
30 lines (24 sloc)  1.05 KB

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test

# Команда `chmod +x gradlew` делает файл gradlew исполняемым в linux. 
# Команда `./gradlew test` собирает ваш проект и запускает тесты.
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
You have no unread notifications
